CREATE DATABASE MOVIE_TICKET_MANAGEMENT;
USE MOVIE_TICKET_MANAGEMENT;

CREATE TABLE THEATRE(THEATRE_ID INT PRIMARY KEY, THEATRE_NAME VARCHAR(10), LOCATION VARCHAR(20));
CREATE TABLE MOVIE_AVAIL(THEATRE_ID INT, MOVIE_AVAILABILITY VARCHAR(20), FOREIGN KEY(THEATRE_ID) REFERENCES THEATRE(THEATRE_ID));